name: pr-validation-path
description: Check if the pull request can be created from source branch to dest branch
author: David Márquez

branding:
  icon: git-pull-request
  color: blue

inputs:
  github-token:
    description: The `GITHUB_TOKEN` secret.
    required: true
  config-path:
    description: The optional configuration file path.
    default: .github/source-dest.yml
    
runs:
  using: 'node12'
  main: 'index.js'