name: pr-validation-path
description: Check if the pull request can be created from source branch to dest branch
author: David Márquez

branding:
  icon: git-pull-request
  color: blue

inputs:
  target-branch:
    description: The target branch
    required: true
  allowed-branches:
    description: The allowed branches
    required: true
    
runs:
  using: 'node12'
  main: 'index.js'